# Generated by Django 5.1.6 on 2025-10-25 17:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('confidence', models.FloatField()),
                ('image_path', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('crash', 'Crash Detected'), ('no_crash', 'No Crash')], max_length=20)),
                ('crash_detected', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
