# Generated by Django 6.0.1 on 2026-02-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disgrasapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='videos/')),
                ('processed_video', models.FileField(blank=True, null=True, upload_to='processed_videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('crash_detected', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Detection',
        ),
    ]
