# Generated by Django 6.0.1 on 2026-02-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disgrasapp', '0002_videoupload_delete_detection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoupload',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='videoupload',
            name='processing_complete',
            field=models.BooleanField(default=False),
        ),
    ]
